sudo: false
cache: pip
language: python
python:
 - "2.7"
 - "3.3"
 - "3.4"
 - "3.5"
 - "3.6"
env:
  global:
   - secure: Qx5oW3Rgo1SMhrM0G/JHyFqaMll74W2Lgkx8tdDzrciMALQPgXMoVpKQJ/DIbKaiKNO5Q2MpwVr/uYviigMH09xwp5jXI3oeLqGyUBCipb4zsLTPYipVvrE1BbNsR7f+/TBQOufS64mu8thppfgvUYnivIlgVtt5RRuRS0ysfHMQxVKsmna+5CRtMkiKOz+0HL1uteeLfxN/I1wDehtRIyer8/4CbV0u2s3wGS+PZmt7xvGqWezh43x2DmthSsBDuZDDQ9NOF4f2ZxGx3bNIyZjbAOSZh/A4aW0wD3jQqVpFEygQdzgjN+L0S4jtLadCscYWSylw1h1uqG88z3ztu9MjeXOVOQqY8SxGWwEQACFWFTGoEC+9I0gppRZzksBwOmZ5FU/dUgE4lSkEJhbYoMFqNytlng61qdTxWaN7HxLjCE/ElvlZWhHCaLtWfsfauFus8SP0NTy4viT4flZgAzdCAaQVBN4tUU0fWPOzURrEgZP3wcYu6R4uEEUl+OtoW0uMS9RyRpIFkJvskMLg6ZRQI1evVhSouuomPpcjYy9pT4w1zG5hqaswsj1Z96QZXgkyFNVBPSwmkx9W70nP4fGvb2ue40TDOnTmRf0XJXy1ZwHlG1i6llQ5IqvhC+92MQkAF3DswP9TBQnshBDeQj0TlAMD48pdgNUUClJ+1OQ=
script:
 - pip install coverage
 - coverage run setup.py test
after_success:
 - pip install coveralls
 - coveralls
deploy:
  provider: pypi
  user: gebn
  password:
    secure: Gd5M8NNgkZ6kY9yL1wvreIhRfYD0E4oI+G3k6H8jr8pSRoqJIkKFlqK7iZ8WjhDSKI358o5b+xnZSgaqEckl47MFA7bxMoI8aCWPhBAcUwk0SE+XdjUwIejuiXFukwrVS4iDTmKHKIjY6aAVJWHsGnCFgURjhPisMagmtkKh5pdiNQFo/uQ8B/nIEnUPYJ8JAZaZ7AhhZ5bJ4zcBu6GJAEzFpIwNaCvRKjurFombG1bwRVLzMqJrNhcnpQfXU63/nIhrKdIQMgJ2j2NGrpiuEsvCGYKEc3mXqGrGvgyIICh3s8KZVLEhEt6eVsNg3DegMm52B1rwWALsHsG3jBu7w2zBcx1iKW9/wLL/SSaHMU4sW0o/xOcHDkw3UjfcfrP56tzJWELeL6smdRkdQVBem5FvZdK+Ry62/9/lkYV6BrPvKJq23lYRMmO/tqtt16WX0e9gB96HNfn42O+j7/SG9PWMcTu6t64c9zvxdsY/SF3NC/iYa3xRkJG9NCikfsDGx1m8eMRUZR7PpL15QIs3yXRqDu7gvkviTM0Ih4COMGzAWANfdLhk7pxhAxebO7owqjosIO9nNbHVK/N6L2PO1VaX5K6dfjo0qWPk+d90xAo9vZWyUFuH9/sFPHKWpxXI1w769brNxW7n/V7BCWNgVzaogazLryVsEE3jZfsbg+4=
  on:
    tags: true
    python: 2.7
    distributions: sdist bdist_wheel
    repo: gebn/chandl
addons:
  coverity_scan:
    project:
      name: gebn/chandl
      description: A lightweight tool for parsing and downloading 4chan threads.
    notification_email: oss@gebn.co.uk
    build_command_prepend: make clean
    build_command: python -m compileall chandl
    branch_pattern: master
